# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab10de26eb98dcdbfd4e667abd20d7fd61c0b9e3ac8583556cacd6041829de02899cfe4096db7fb232865d144424b2c963941eb77fb43c7b7064a751d42406fc

test:
  secret_key_base: 8fdd59721fbfcfce6f3a3614291af80a44c4e969b2d1b601941e63158dfc5bbc286399a8e705878e751d88d6a523a8b921034b9ef354e28008fe45f1cb372a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
